### ISSUE TITLE
Show warning/info when deleting disk/nic from running VM

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui#100]
@lizsurette If I delete (and in the future edit) NIC or Disk from VM  ( https://github.com/kubevirt/web-ui/pull/91 ) and the VM is running, the changes will not affect the running instance. Should we show warning or info that the changes will be applied to the new instance ?

**Comment by lizsurette** [comment]
@rawagner Definitely. We did some [thinking on a similar workflow for oVirt](https://github.com/lizsurette/ovirt-design/blob/8406b8b1c13d9dd86ba1ce8a4d5aa19723b0d8cd/user-portal/edit-virtual-machine.md) where is the user makes a change that won't be applied until after a restart.

Do you think something like this would work where we let the user know that this change won't be applied until after a restart and then maybe some sort of notification above the table view?

oVirt Example confirmation modal:
![screen shot 2018-11-08 at 11 14 59 am](https://user-images.githubusercontent.com/208455/48211519-a417b380-e347-11e8-936d-9d77e6fbbe53.png)

oVirt Example inline notification:
![screen shot 2018-11-08 at 11 15 23 am](https://user-images.githubusercontent.com/208455/48211526-aa0d9480-e347-11e8-8d19-7d7b13d2376a.png)

@andybraren - What do you think?

**Comment by andybraren** [comment]
Sorry I'm late to this discussion. Good question, and I agree this is something we need to design for.

Here's the current NIC editor, for those following:

![question-nic-click-confirm](https://user-images.githubusercontent.com/9122899/49113759-59ad9680-f264-11e8-82ce-96cd8e627a17.png)

@lizsurette In oVirt that confirmation modal seems to appear immediately after clicking the blue confirm button. I'm mostly okay with that, but if users click "Save Changes" and continue modifying other NICs/Disks I wouldn't want that modal to appear again. If it did there's a high likelihood they'd accidentally click the primary action (restart) while moving too quickly in annoyance.

I'd rather provide ambient indicators, like the inline notification, but also something more persistent. I think the VM's Status should change from "Running" with a green `pficon-on-running` icon to something slightly less positive, like an orange icon with an asterisk next to "Running", or maybe "Pending" if that's more appropriate. This feels like a use case PatternFly/OKD should have an icon for, but I'm not finding any that quite fit this scenario.

Here's a mockup of some Status ideas:

![question-vm-changes-pending-status](https://user-images.githubusercontent.com/9122899/49116156-c461d080-f26a-11e8-908a-b0df98deae57.png)

Clicking the status could either bring the user to a log message describing the need to restart (similar to the way actual errors work) or display a tooltip with a brief message.

Does this make sense? I can get started mocking up the inline notification in the meanwhile.

**Comment by lizsurette** [comment]
> Does this make sense? I can get started mocking up the inline notification in the meanwhile.

@andybraren I think a combination of the icon/state change and an inline notification would make it clear. You're right that we could probably avoid the pop-up and just let the user know that the changes haven't taken place yet and provide a quick way to restart via a link in the notification.

**Comment by andybraren** [comment]
I've [proposed](https://github.com/kubevirt/web-ui-design/pull/21) a new status icon in the design repo. It looks like this:

![status-pending-changes](https://user-images.githubusercontent.com/9122899/49529641-79584680-f884-11e8-8f2a-a243e388c463.png)

And here's what an inline notification could look like immediately after a NIC is added/modified. I think it should persist across all tab views, including the Overview, until the VM has been restarted.

![4-1-3-add-edit-changed](https://user-images.githubusercontent.com/9122899/49530234-d6a0c780-f885-11e8-9fe7-8f123be7cf3d.png)
