### ISSUE TITLE
Rename Networks to NICs in VM details page? 

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui#103]
@lizsurette there was a confusion about what Networks in VM Details page represents and it was suggested that we maybe want to rename it to NICs/Network Interfaces...

**Comment by lizsurette** [comment]
@rawagner Makes sense to update it if it's causing confusion. I wonder if we should stay consistent with this tab name and the Step 2 name in the wizard. Would it make sense to call both "Network Interfaces"?

@andybraren @jelkosz

**Comment by andybraren** [comment]
@lizsurette Hmm. If we want both the Create VM wizard and VM Details tab to use the same label, "Network Interfaces" is so long that it may look out of place and cause some wrapping in the wizard.

"NICs" would be a more compact alternative (and might not need translation?) but if that tab in the wizard ever extends to include more than solely "Network Interface Cards/Controllers" then that label may not be generic enough.

I'd lean toward either:
1. "Networking" in the Create VM wizard and "NICs" in VM details
2. "NICs" in both the Create VM wizard and VM details (if appropriate)

**Comment by rawagner** [comment]
I like the first option. It is same as Storage in CreateVMWizard and Disks in VM Details. Storage may also, in the future, represent more that just adding disks.

**Comment by lizsurette** [comment]
@andybraren @rawagner Sounds great to me!

**Comment by rawagner** [comment]
PR https://github.com/kubevirt/web-ui/pull/107
