### ISSUE TITLE
Record the template namespace when preparing VM

### ISSUE THREAD

**Issue by MarSik** [kubevirt/web-ui#133]
A VM created from template has a `vm.cnv.io/template: template_name` label. But it should store the namespace as well. I propose using a second label `vm.cnv.io/template-namespace: template_namespace`.

If the namespace is defined, then we know where to look explicitly, but when it is not, then the template is expected to belong to the same namespace as the VM.

**Comment by rawagner** [comment]
fixed with https://github.com/kubevirt/web-ui-components/pull/214
