### ISSUE TITLE
openshiftvirt branding: fix logo/text

### ISSUE THREAD

**Issue by mareklibra** [kubevirt/web-ui#167]
With the new layout, the `Virtualization` text is not fully visible in `openshiftvirt` branding:

![openshiftvirt](https://user-images.githubusercontent.com/17194943/50951807-ca281400-14ae-11e9-8d50-b78cd49b1dc8.png)

**Comment by matthewcarleton** [comment]
Thanks Marek! I am aware of this and have been talking to Patrick Riley about a fix :)

**Comment by rawagner** [comment]
as a quickfix for 1.4 we can lower font size from 17px to 15px. https://github.com/kubevirt/web-ui/pull/179
