### ISSUE TITLE
Missing 'all projects'

### ISSUE THREAD

**Issue by e-minguez** [kubevirt/web-ui#316]
As a cluster-admin I want to be able to see all the $objects in my cluster. Before there was an 'all projects' item in the dropdown menu, but now you can only select individual projects:

![not_all](https://user-images.githubusercontent.com/346758/56288457-21c5c380-611f-11e9-8aa7-d40263fe0f4e.png)

I'm using this image:

```
$ oc get -o yaml $(oc get pod --selector component=ui -o name)  | grep image
    image: quay.io/kubevirt/kubevirt-web-ui:latest
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
    image: quay.io/kubevirt/kubevirt-web-ui:latest
    imageID: quay.io/kubevirt/kubevirt-web-ui@sha256:55a2058966f6e2f57eb0cda3a45ab12f2a3697ca6a41cbd81b8cff7e99843642
```

**Comment by jelkosz** [comment]
I see that on the latest build in pods. Are you sure it is not just down there available when you scroll down?

**Comment by e-minguez** [comment]
It works after refreshing the UI, sorry for the noise.
