### ISSUE TITLE
Updates for node maintenance action

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui#333]
Please correct me if I'm wrong, but my understanding is that the "Start Maintenance" action will only be available to hosts in Metal³, and not nodes?

Without the data rebuilding logic, this modal looks like what I would imagine a "Drain Node" modal would look like that triggers something like `kubectl drain $nodename`. That's probably fine for OKD, but IIRC draining a node without the data rebuilding logic isn't recommended in Metal³ since moving storage pods immediately could be a very long and expensive operation.

Regardless of that confusion, here's a mockup of how we could show a Maintenance reason for hosts in the UI. I agree that showing it when clicking the `Under maintenance` status is the best option. If no reason is given, nothing is shown in that area of the popover.

![2b-1a-maint-modal](https://user-images.githubusercontent.com/9122899/56677185-f77b8500-668d-11e9-8429-cb4f0ae6e8cf.png)

![2a-2b-maint-status-messages](https://user-images.githubusercontent.com/9122899/56677163-ed598680-668d-11e9-875b-9dba89f90310.png)

_Originally posted by @andybraren in https://github.com/kubevirt/web-ui/pull/328#issuecomment-486444934_

**Comment by andybraren** [comment]
My confusion about whether "maintenance" is a host or a node action is cleared up. It's definitely a node action.

This issue can probably be closed unless we want to track the "Maintenance reason" part of this design (which should include the new [Status Popover](http://openshift.github.io/openshift-origin-design/web-console/4.0-designs/status/status#status-popovers) pattern).
