### ISSUE TITLE
wizard fails when behind a proxy

### ISSUE THREAD

**Issue by karmab** [kubevirt/web-ui#35]
when trying to launch a vm through the wizard, the vm doesnt get created, i get the following error after putting all data
"Cant find resource" 
tested with a (ssh) sock proxy

**Comment by ohadlevy** [comment]
can you provide more details on your setup? e.g. SSL etc - also, do you get a more detailed error message on your browser?

**Comment by karmab** [comment]
- i dont use ssl, i ran on openshift
- i dont see any messages on the kubevirt-ui pod

![image](https://user-images.githubusercontent.com/1840387/46610309-ab5e5e00-cb0a-11e8-915c-79d04391c0b6.png)

![image](https://user-images.githubusercontent.com/1840387/46610318-b3b69900-cb0a-11e8-95a2-d9e34c1c18d0.png)

**Comment by jelkosz** [comment]
@karmab what is the version of your openshift? We had a bug that the wizard worked well on openshift 3.10 and failed on this error on 3.11. This is the fix (https://github.com/kubevirt/web-ui-components/pull/31), build should come soon. Just please confirm, the difference between env where it works and where it does not is not only the proxy, but also the openshift version, right?

**Comment by karmab** [comment]
retested today with latest and issue is no longer there !
