### ISSUE TITLE
Namespaces dropdown empty in VM wizard

### ISSUE THREAD

**Issue by ramondg** [kubevirt/web-ui#390]
Seems like namespaces in the Create VM from wizard window are not properly fetched. The list is empty. Deploying a VM from yaml works like a charm!
![kubevirt-web-ui](https://user-images.githubusercontent.com/12154739/58136993-8c8f8080-7c30-11e9-80bb-60ea4c39f723.PNG)

**Comment by suomiy** [comment]
this may be due to the permissions, we should use projects in that case

**Comment by ramondg** [comment]
I did not see any 403 permission denied errors looking at the network stream. Also, I have loaded the admin credentials. Furthermore, I can create a VM through a yaml file and browse all the namespaces..

**Comment by suomiy** [comment]
hmm, that is weird. Did the other fields get populated successfully ?

**Comment by ramondg** [comment]
Yes they did, can you point out where in the code this data is being loaded?

**Comment by suomiy** [comment]
here: https://github.com/kubevirt/web-ui/blob/master/frontend/public/kubevirt/components/modals/create-vm-modal.js#L20
