### ISSUE TITLE
Does this Web UI only works with Open Shift ? 

### ISSUE THREAD

**Issue by sacashgit** [kubevirt/web-ui#418]
We have deployed Kubevirt (following the kubevirt.io docs) on open source kubernetes and were trying to see if we could get the WebUI on top it. The instructions listed here are all for Open Shift. Does the Web UI for Kubevirt works on open source kubernetes and where should we look for instructions?

**Comment by rawagner** [comment]
Hi @sacashgit, web-ui requires OKD/OpenShift as we use some CRDs from there (templates).

This project is actually deprecated in favor of OKD UI https://github.com/openshift/console where kubevirt ui is included as plugin https://github.com/openshift/console/tree/master/frontend/packages/kubevirt-plugin . You should be able to deploy OKD on kubernetes too https://github.com/openshift/console#native-kubernetes but kubevirt-plugin still expects that there will be Templates CRD. We will probably remove this dependency in the future, but I'm not able to give you any time estimates.

**Comment by mareklibra** [comment]
Dupplicate issue: https://github.com/kubevirt/web-ui-operator/issues/94

**Comment by sacashgit** [comment]
> Hi @sacashgit, web-ui requires OKD/OpenShift as we use some CRDs from there (templates).
> 
> This project is actually deprecated in favor of OKD UI https://github.com/openshift/console where kubevirt ui is included as plugin https://github.com/openshift/console/tree/master/frontend/packages/kubevirt-plugin . You should be able to deploy OKD on kubernetes too https://github.com/openshift/console#native-kubernetes but kubevirt-plugin still expects that there will be Templates CRD. We will probably remove this dependency in the future, but I'm not able to give you any time estimates.

thanks @rawagner for your response. I thought of trying the option you high lighted but the instructions were bit vague there and I wasnt even sure if this is meant for native K8 or still dependencies with open shift.  Would you care to provide additional steps/guidance if I want to test the UI on native kubernetes where I already have kubevirt working well ?
