### ISSUE TITLE
consoles: add spinner if VM is starting

### ISSUE THREAD

**Issue by mareklibra** [kubevirt/web-ui#45]
The VM console (recently VNC, but others will come) requires running VMI to connect to. If none is available, the user is instructed to start the VM.

For the case when VMI is not running, but VM start is in progress (like `scheduling`), the message should reflect this phase and show spinner.

**Comment by jelkosz** [comment]
@lizsurette do you agree a spinner is a good choice here?

**Comment by lizsurette** [comment]
@jelkosz @mareklibra We are going to do a quick pass at a design for this flow and will share soon!

**Comment by yfrimanm** [comment]
Hi @mareklibra, @jelkosz, @lizsurette, please take a look at these 2 options: 
![vm_startinprogop1](https://user-images.githubusercontent.com/44577420/47655807-7b006180-db96-11e8-9266-f0a6fd70cf48.png)
![vm_startinprogop2](https://user-images.githubusercontent.com/44577420/47655808-7b98f800-db96-11e8-96a6-6df2bb8a49a8.png)

Ref. to the PF spinner: https://www.patternfly.org/pattern-library/widgets/#spinner

**Comment by ohadlevy** [comment]
do we have a way to do proper time estimates? AFAIU we can't have a reliable progress indication (e.g. not time based nor step 1 / 10) @jelkosz ?

**Comment by jelkosz** [comment]
I dont thinw we have anything reliable.

**Comment by yfrimanm** [comment]
In that case we might just omit this line?

**Comment by yfrimanm** [comment]
<img width="1257" alt="vm_startinprogop1 2" src="https://user-images.githubusercontent.com/44577420/47665961-1ac7ea80-dbab-11e8-8988-db0bfa2af6b6.png">
<img width="1258" alt="vm_startinprogop2 2" src="https://user-images.githubusercontent.com/44577420/47665962-1b608100-dbab-11e8-96e9-754c8b58f1fa.png">

**Comment by ohadlevy** [comment]
In the first image, what does the progress bar indicate? How do you
calculate in which position should it be at?

**Comment by yfrimanm** [comment]
It should indicate the remaining time for the console to be available.

**Comment by jelkosz** [comment]
I don't think there is any way for us to guesstimate the remaining time, unless @mareklibra knows something more.

**Comment by lizsurette** [comment]
@rawagner Great point, we should probably use the Tectonic loading GIF rather than PatternFly until we switch all of the loading GIFs in the console over to PatternFly :)

**Comment by mareklibra** [comment]
> I don't think there is any way for us to guesstimate the remaining time, unless @mareklibra knows something more.

We can "step over" phases required for launching a VM but I don't think this make any sense from the user perspective (some of them are super fast, some can get stuck). So I am for the neutral spinner/GIF.

**Comment by mareklibra** [comment]
Following is for a new GH issue, but is related.
When developing the `Consoles` tab, I faced an issue when the pod got stuck in the `Scheduling` phase due to cluster misconfiguration (but could be whatever else).
I had feeling I should keep waiting. After curious visiting the `Events` page I saw it would take forever. We should reflect such issues in the UI more visibly, not just part of the `Events`.

**Comment by lizsurette** [comment]
> Following is for a new GH issue, but is related.
> When developing the `Consoles` tab, I faced an issue when the pod got stuck in the `Scheduling` phase due to cluster misconfiguration (but could be whatever else).
> I had feeling I should keep waiting. After curious visiting the `Events` page I saw it would take forever. We should reflect such issues in the UI more visibly, not just part of the `Events`.

@mareklibra This came up in another thread as well as @rawagner was trying to run a VM with an additional disk which uses the volume PVC type (VM and PVC definition attached). Turns out it was a permissions issue that was shown in the Events, but wasn't surfaced well to the user. Would you guys like me to log a different issue for these cases? Or is there something that already exists to track it?

**Comment by lizsurette** [comment]
> So I am for the neutral spinner/GIF.

+1 to simply sticking with the loading GIF rather than trying to introduce any sort of progress for now.

**Comment by jelkosz** [comment]
> @mareklibra This came up in another thread as well as @rawagner was trying to run a VM with an additional disk which uses the volume PVC type (VM and PVC definition attached). Turns out it was a permissions issue that was shown in the Events, but wasn't surfaced well to the user. Would you guys like me to log a different issue for these cases? Or is there something that already exists to track it?

just opened it: https://github.com/kubevirt/web-ui/issues/77
