### ISSUE TITLE
"At least one bootable NIC has to be defined for PXE boot" before create a bootable nic

### ISSUE THREAD

**Issue by gouyang** [kubevirt/web-ui#51]
The message appears immediately on network page, it should only pop up when no bootable nic is created by clicking "Create virtual machine".

**Comment by lizsurette** [comment]
We are hoping to allow the user to "Create Virtual Machine" at any time after the basic settings are selected. This is a good point though that if the user chooses to provision the VM with PXE boot, maybe we should disable this button until after they have defined the bootable NIC.

**Comment by gouyang** [comment]
I was thinking moving "Create Virtual Machine" to a separate page, put it on network page looks not quite logically, usually on network page it should be a "Next" button.

**Comment by lizsurette** [comment]
Well the goal behind having it here would be to allow the user to create the VM with just the basic settings and not having filled out the Network or Storage settings. It would definitely be a secondary use case which is why the Next button should have the primary blue.

**Comment by gouyang** [comment]
it's not happened any more.
