### ISSUE TITLE
Going back to "Basic Settings" step results in "Next" button being disabled even though required fields are filled

### ISSUE THREAD

**Issue by lizsurette** [kubevirt/web-ui#57]
Steps to reproduce:

1) Fill out required Basic Settings, including PXE as provision source.
2) Click Next.
3) Notice you need to supply a bootable NIC before moving forward so the Next button is disabled.
4) Click "Back" incase you want to change basic settings.
5) Now the "Next" button is disabled even though all of the required information is filled out, when it should be enabled:
<img width="935" alt="screen shot 2018-10-24 at 3 01 38 pm" src="https://user-images.githubusercontent.com/208455/47455099-fc26b580-d79e-11e8-9237-12d2fd74d989.png">

**Comment by jelkosz** [comment]
It happens when you have the "project" selected so you don't have the "namespace" field in the wizard.

**Comment by rawagner** [comment]
Ok, I can reproduce on Marek's upshift env but cant locally with latest master so it seems that this is already fixed.

**Comment by lizsurette** [comment]
@rawagner thanks for testing on master. I'll close this one as fixed.

**Comment by jelkosz** [comment]
@rawagner but we would like to have this fixed in the 1.3 branch to make sure our stable branch is, you know, stable :) Reopening to avoid loosing it from radar.

**Comment by rawagner** [comment]
fixed in 1.3.-9
