### ISSUE TITLE
Styling issues in the Network configuration step of Create VM Wizard

### ISSUE THREAD

**Issue by lizsurette** [kubevirt/web-ui#59]
It seems as though some underlying styling is missing for the Network configuration table. If I compare what was available in Cosmos for review which looked like it had the right styling:
<img width="1028" alt="screen shot 2018-10-24 at 3 26 56 pm" src="https://user-images.githubusercontent.com/208455/47456052-76f0d000-d7a1-11e8-91cb-80a7b826b4c2.png">

with what I see currently:
![screen shot 2018-10-24 at 3 27 21 pm](https://user-images.githubusercontent.com/208455/47456077-8cfe9080-d7a1-11e8-9b2f-ba1d690e36e9.png)

A few things seem off:
- Table header row background color
- Table vertical column seperators
- Positioning of "create" and "cancel" buttons for adding a new NIC

**Comment by ohadlevy** [comment]
@lizsurette just wondering, should this really be red / error? every time I get to this stage it feels like I did something wrong, would it be possible to either:
1. change to warning?
2. change the wizard to simply ask you to chose it?
2a. in case ND doesn't exist guide you to create it?

**Comment by lizsurette** [comment]
@rawagner thanks for the update! We can close this if it's already being tracked in a task, whatever you'd like.

@ohadlevy I've been wondering the exact same thing. It's nice that it's so in your face since it's something you absolutely need to do, but I have been thinking maybe we should bump it down to a warning and see if that has the same effect without feeling like I did something wrong :) @rawagner what do you think?

**Comment by rawagner** [comment]
@lizsurette @ohadlevy please take a look at https://github.com/kubevirt/web-ui-components/pull/55 and [storybook]( https://agitated-fermi-950e49.netlify.com/?component=Wizards%2FCreateVmWizard%2Fj&fixture=namespaces) - error is handled differently. There is a dropdown button marked as required and validation message underneath. Do you think it is better ? Or maybe marking the dropdown as required is enough and there is no need for the validation message ?

**Comment by lizsurette** [comment]
@rawagner I think this works great and I know is the design that Andy was driving towards. What do you think @ohadlevy?
