### ISSUE TITLE
remove the context switcher from the masthead

### ISSUE THREAD

**Issue by jelkosz** [kubevirt/web-ui#67]
It is not a good idea to have the context switcher in the masthead since it can navigate you out from the virtualization view and there will be no way back using the masthead.

**Comment by mareklibra** [comment]
Will be fixed via ConfigMap (created by kubevirt-ansible)

**Comment by mareklibra** [comment]
Fixed by: https://github.com/kubevirt/kubevirt-ansible/pull/432

**Comment by mareklibra** [comment]
Merged
