### ISSUE TITLE
Enable openshift/console pages

### ISSUE THREAD

**Issue by mareklibra** [kubevirt/web-ui#69]
Enable additional openshift/console pages in left-side menu in kubevirt/web-ui.

Some of the pages were re-enabled within PR #38.
Following extra have been identified so far:
- Administration
- Monitoring

**Comment by mareklibra** [comment]
Cc @jelkosz , @ohadlevy, @mgoldboi

**Comment by mareklibra** [comment]
openshift/console:
![openshift-console](https://user-images.githubusercontent.com/17194943/47620608-3f10c200-daec-11e8-86ae-e791510a7ce1.png)

kubevirt/web-ui:
![kubevirt-web-ui](https://user-images.githubusercontent.com/17194943/47620609-3f10c200-daec-11e8-8138-74f00fd8f477.png)

**Comment by lizsurette** [comment]
@mareklibra Looks good to me! I do think adding Monitoring & Administration would be nice too.

**Comment by mareklibra** [comment]
PRs merged
