### ISSUE TITLE
Navigation should highlight when primary nav item is selected

### ISSUE THREAD

**Issue by lizsurette** [kubevirt/web-ui#8]
The navigation should be sure to use the correct highlighting to let the user know which section is selected:
<img width="238" alt="screen shot 2018-09-18 at 10 37 42 am" src="https://user-images.githubusercontent.com/208455/45695193-e7fff080-bb2e-11e8-8e2b-cb3528837081.png">

**Comment by jelkosz** [comment]
since it has been decided to move the primary nav item of VMs under the workloads, this issue is not relevant anymore - closing.
