### ISSUE TITLE
Improve tectonic to allow events from more resources

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui#84]
Currently you can subscribe to one resource events or 'all'. We should improve this and allow subscribing to more than one resource. It will be handy to subscribe to VM and VMI events (maybe also VM's Pod)

**Comment by mareklibra** [comment]
@rawagner, still on the wish-list, right?

**Comment by rawagner** [comment]
Yes, this will have to happen when moving our functionality to upstream openshift ui.

/remove-lifecycle rotten
/reopen
