### ISSUE TITLE
Validate the VM subdomain immediately

### ISSUE THREAD

**Issue by gouyang** [kubevirt/web-ui#92]
Currently, if an invalid VM name is given, it's throwing the error at the last step. It's better to pop up such error immediately.

**Comment by andybraren** [comment]
Maybe something like the below, which matches [PatternFly 3's guidelines](https://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/)?

If the validation we need is pretty basic, we could also investigate [HTML5's input pattern attribute](https://www.w3schools.com/tags/att_input_pattern.asp) for basic regex matching and leave server-side checks for the final "Review" step.

![2-1d-basic-error](https://user-images.githubusercontent.com/9122899/48230693-efe35080-e379-11e8-89c9-b9ec240f207b.png)

**Comment by gouyang** [comment]
the validation is added.
